version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/payment_gateway
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
